package Model;


// Generated May 26, 2011 1:25:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AppPropsInfoId generated by hbm2java
 */
public class AppPropsInfoId implements java.io.Serializable {

	private String propsNm;
	private String propsValueDesc;
	private String propsDtlTxt;
	private Date propsDt;

	public AppPropsInfoId() {
	}

	public AppPropsInfoId(String propsNm, String propsValueDesc,
			String propsDtlTxt, Date propsDt) {
		this.propsNm = propsNm;
		this.propsValueDesc = propsValueDesc;
		this.propsDtlTxt = propsDtlTxt;
		this.propsDt = propsDt;
	}

	public String getPropsNm() {
		return this.propsNm;
	}

	public void setPropsNm(String propsNm) {
		this.propsNm = propsNm;
	}

	public String getPropsValueDesc() {
		return this.propsValueDesc;
	}

	public void setPropsValueDesc(String propsValueDesc) {
		this.propsValueDesc = propsValueDesc;
	}

	public String getPropsDtlTxt() {
		return this.propsDtlTxt;
	}

	public void setPropsDtlTxt(String propsDtlTxt) {
		this.propsDtlTxt = propsDtlTxt;
	}

	public Date getPropsDt() {
		return this.propsDt;
	}

	public void setPropsDt(Date propsDt) {
		this.propsDt = propsDt;
	}

	

}
