package Model;



// Generated May 26, 2011 1:25:44 PM by Hibernate Tools 3.4.0.CR1

/**
 * AppPropsInfo generated by hbm2java
 */
public class AppPropsInfo implements java.io.Serializable {

	private AppPropsInfoId id;

	public AppPropsInfo() {
	}

	public AppPropsInfo(AppPropsInfoId id) {
		this.id = id;
	}

	public AppPropsInfoId getId() {
		return this.id;
	}

	public void setId(AppPropsInfoId id) {
		this.id = id;
	}

}
