package OneToMany;



// Generated May 24, 2011 7:06:05 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * BatchEventLog generated by hbm2java
 */
public class BatchEventLog implements java.io.Serializable {

	private BigDecimal belEventSeqNbr;
	private String belEventNm;
	private Serializable belEventStartTs;
	private Serializable belEventEndTs;
	private String belEventStatus;
	private BigDecimal belRecordCnt;

	public BatchEventLog() {
	}

	public BatchEventLog(BigDecimal belEventSeqNbr) {
		this.belEventSeqNbr = belEventSeqNbr;
	}

	public BatchEventLog(BigDecimal belEventSeqNbr, String belEventNm,
			Serializable belEventStartTs, Serializable belEventEndTs,
			String belEventStatus, BigDecimal belRecordCnt) {
		this.belEventSeqNbr = belEventSeqNbr;
		this.belEventNm = belEventNm;
		this.belEventStartTs = belEventStartTs;
		this.belEventEndTs = belEventEndTs;
		this.belEventStatus = belEventStatus;
		this.belRecordCnt = belRecordCnt;
	}

	public BigDecimal getBelEventSeqNbr() {
		return this.belEventSeqNbr;
	}

	public void setBelEventSeqNbr(BigDecimal belEventSeqNbr) {
		this.belEventSeqNbr = belEventSeqNbr;
	}

	public String getBelEventNm() {
		return this.belEventNm;
	}

	public void setBelEventNm(String belEventNm) {
		this.belEventNm = belEventNm;
	}

	public Serializable getBelEventStartTs() {
		return this.belEventStartTs;
	}

	public void setBelEventStartTs(Serializable belEventStartTs) {
		this.belEventStartTs = belEventStartTs;
	}

	public Serializable getBelEventEndTs() {
		return this.belEventEndTs;
	}

	public void setBelEventEndTs(Serializable belEventEndTs) {
		this.belEventEndTs = belEventEndTs;
	}

	public String getBelEventStatus() {
		return this.belEventStatus;
	}

	public void setBelEventStatus(String belEventStatus) {
		this.belEventStatus = belEventStatus;
	}

	public BigDecimal getBelRecordCnt() {
		return this.belRecordCnt;
	}

	public void setBelRecordCnt(BigDecimal belRecordCnt) {
		this.belRecordCnt = belRecordCnt;
	}

}
