package OneToMany;



// Generated May 24, 2011 7:06:05 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CreditCardAuth generated by hbm2java
 */
public class CreditCardAuth implements java.io.Serializable {

	private BigDecimal ccaAuthSeqNbr;
	private CreditCardInfo creditCardInfo;
	private String ccaAuthTypCd;
	private BigDecimal ccaAuthAmt;
	private String ccaAuthCd;
	private String ccaResponseCd;
	private String ccaResponseDesc;
	private Date ccaCreatedDt;
	private Set<OneshotCcTrans> oneshotCcTranses = new HashSet<OneshotCcTrans>(
			0);

	public CreditCardAuth() {
	}

	public CreditCardAuth(BigDecimal ccaAuthSeqNbr) {
		this.ccaAuthSeqNbr = ccaAuthSeqNbr;
	}

	public CreditCardAuth(BigDecimal ccaAuthSeqNbr,
			CreditCardInfo creditCardInfo, String ccaAuthTypCd,
			BigDecimal ccaAuthAmt, String ccaAuthCd, String ccaResponseCd,
			String ccaResponseDesc, Date ccaCreatedDt,
			Set<OneshotCcTrans> oneshotCcTranses) {
		this.ccaAuthSeqNbr = ccaAuthSeqNbr;
		this.creditCardInfo = creditCardInfo;
		this.ccaAuthTypCd = ccaAuthTypCd;
		this.ccaAuthAmt = ccaAuthAmt;
		this.ccaAuthCd = ccaAuthCd;
		this.ccaResponseCd = ccaResponseCd;
		this.ccaResponseDesc = ccaResponseDesc;
		this.ccaCreatedDt = ccaCreatedDt;
		this.oneshotCcTranses = oneshotCcTranses;
	}

	public BigDecimal getCcaAuthSeqNbr() {
		return this.ccaAuthSeqNbr;
	}

	public void setCcaAuthSeqNbr(BigDecimal ccaAuthSeqNbr) {
		this.ccaAuthSeqNbr = ccaAuthSeqNbr;
	}

	public CreditCardInfo getCreditCardInfo() {
		return this.creditCardInfo;
	}

	public void setCreditCardInfo(CreditCardInfo creditCardInfo) {
		this.creditCardInfo = creditCardInfo;
	}

	public String getCcaAuthTypCd() {
		return this.ccaAuthTypCd;
	}

	public void setCcaAuthTypCd(String ccaAuthTypCd) {
		this.ccaAuthTypCd = ccaAuthTypCd;
	}

	public BigDecimal getCcaAuthAmt() {
		return this.ccaAuthAmt;
	}

	public void setCcaAuthAmt(BigDecimal ccaAuthAmt) {
		this.ccaAuthAmt = ccaAuthAmt;
	}

	public String getCcaAuthCd() {
		return this.ccaAuthCd;
	}

	public void setCcaAuthCd(String ccaAuthCd) {
		this.ccaAuthCd = ccaAuthCd;
	}

	public String getCcaResponseCd() {
		return this.ccaResponseCd;
	}

	public void setCcaResponseCd(String ccaResponseCd) {
		this.ccaResponseCd = ccaResponseCd;
	}

	public String getCcaResponseDesc() {
		return this.ccaResponseDesc;
	}

	public void setCcaResponseDesc(String ccaResponseDesc) {
		this.ccaResponseDesc = ccaResponseDesc;
	}

	public Date getCcaCreatedDt() {
		return this.ccaCreatedDt;
	}

	public void setCcaCreatedDt(Date ccaCreatedDt) {
		this.ccaCreatedDt = ccaCreatedDt;
	}

	public Set<OneshotCcTrans> getOneshotCcTranses() {
		return this.oneshotCcTranses;
	}

	public void setOneshotCcTranses(Set<OneshotCcTrans> oneshotCcTranses) {
		this.oneshotCcTranses = oneshotCcTranses;
	}

}
