package OneToMany;



// Generated May 24, 2011 7:06:05 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OneshotCcTrans generated by hbm2java
 */
public class OneshotCcTrans implements java.io.Serializable {

	private BigDecimal octTransSeqNbr;
	private CreditCardInfo creditCardInfo;
	private CreditCardAuth creditCardAuth;
	private BatchFile batchFileByBafSettleFileSeqNbr;
	private BatchFile batchFileByBafReturnFileSeqNbr;
	private String octCustIpAddr;
	private String octPolicyNbr;
	private String octQuoteNbr;
	private String octSourceAppCd;
	private BigDecimal octTransAmt;
	private String octTrackingNbr;
	private String octMerchantNbr;
	private String octTransStatusCd;
	private String octInsuredStCd;
	private String octTransStatusDesc;
	private String octInsuredFrstNm;
	private String octInsuredMidNm;
	private String octInsuredLastNm;
	private Character octSettleInd;
	private Date octTransDt;
	private Date octSettledDt;
	private String octSettleBatchNbr;
	private String octTransUserId;
	private Date octCreatedDt;
	private Date octModifiedDt;
	private String octModifiedUserId;
	private String octAppId;
	private Set<OneshotTransRev> oneshotTransRevs = new HashSet<OneshotTransRev>(
			0);

	public OneshotCcTrans() {
	}

	public OneshotCcTrans(BigDecimal octTransSeqNbr) {
		this.octTransSeqNbr = octTransSeqNbr;
	}

	public OneshotCcTrans(BigDecimal octTransSeqNbr,
			CreditCardInfo creditCardInfo, CreditCardAuth creditCardAuth,
			BatchFile batchFileByBafSettleFileSeqNbr,
			BatchFile batchFileByBafReturnFileSeqNbr, String octCustIpAddr,
			String octPolicyNbr, String octQuoteNbr, String octSourceAppCd,
			BigDecimal octTransAmt, String octTrackingNbr,
			String octMerchantNbr, String octTransStatusCd,
			String octInsuredStCd, String octTransStatusDesc,
			String octInsuredFrstNm, String octInsuredMidNm,
			String octInsuredLastNm, Character octSettleInd, Date octTransDt,
			Date octSettledDt, String octSettleBatchNbr, String octTransUserId,
			Date octCreatedDt, Date octModifiedDt, String octModifiedUserId,
			String octAppId, Set<OneshotTransRev> oneshotTransRevs) {
		this.octTransSeqNbr = octTransSeqNbr;
		this.creditCardInfo = creditCardInfo;
		this.creditCardAuth = creditCardAuth;
		this.batchFileByBafSettleFileSeqNbr = batchFileByBafSettleFileSeqNbr;
		this.batchFileByBafReturnFileSeqNbr = batchFileByBafReturnFileSeqNbr;
		this.octCustIpAddr = octCustIpAddr;
		this.octPolicyNbr = octPolicyNbr;
		this.octQuoteNbr = octQuoteNbr;
		this.octSourceAppCd = octSourceAppCd;
		this.octTransAmt = octTransAmt;
		this.octTrackingNbr = octTrackingNbr;
		this.octMerchantNbr = octMerchantNbr;
		this.octTransStatusCd = octTransStatusCd;
		this.octInsuredStCd = octInsuredStCd;
		this.octTransStatusDesc = octTransStatusDesc;
		this.octInsuredFrstNm = octInsuredFrstNm;
		this.octInsuredMidNm = octInsuredMidNm;
		this.octInsuredLastNm = octInsuredLastNm;
		this.octSettleInd = octSettleInd;
		this.octTransDt = octTransDt;
		this.octSettledDt = octSettledDt;
		this.octSettleBatchNbr = octSettleBatchNbr;
		this.octTransUserId = octTransUserId;
		this.octCreatedDt = octCreatedDt;
		this.octModifiedDt = octModifiedDt;
		this.octModifiedUserId = octModifiedUserId;
		this.octAppId = octAppId;
		this.oneshotTransRevs = oneshotTransRevs;
	}

	public BigDecimal getOctTransSeqNbr() {
		return this.octTransSeqNbr;
	}

	public void setOctTransSeqNbr(BigDecimal octTransSeqNbr) {
		this.octTransSeqNbr = octTransSeqNbr;
	}

	public CreditCardInfo getCreditCardInfo() {
		return this.creditCardInfo;
	}

	public void setCreditCardInfo(CreditCardInfo creditCardInfo) {
		this.creditCardInfo = creditCardInfo;
	}

	public CreditCardAuth getCreditCardAuth() {
		return this.creditCardAuth;
	}

	public void setCreditCardAuth(CreditCardAuth creditCardAuth) {
		this.creditCardAuth = creditCardAuth;
	}

	public BatchFile getBatchFileByBafSettleFileSeqNbr() {
		return this.batchFileByBafSettleFileSeqNbr;
	}

	public void setBatchFileByBafSettleFileSeqNbr(
			BatchFile batchFileByBafSettleFileSeqNbr) {
		this.batchFileByBafSettleFileSeqNbr = batchFileByBafSettleFileSeqNbr;
	}

	public BatchFile getBatchFileByBafReturnFileSeqNbr() {
		return this.batchFileByBafReturnFileSeqNbr;
	}

	public void setBatchFileByBafReturnFileSeqNbr(
			BatchFile batchFileByBafReturnFileSeqNbr) {
		this.batchFileByBafReturnFileSeqNbr = batchFileByBafReturnFileSeqNbr;
	}

	public String getOctCustIpAddr() {
		return this.octCustIpAddr;
	}

	public void setOctCustIpAddr(String octCustIpAddr) {
		this.octCustIpAddr = octCustIpAddr;
	}

	public String getOctPolicyNbr() {
		return this.octPolicyNbr;
	}

	public void setOctPolicyNbr(String octPolicyNbr) {
		this.octPolicyNbr = octPolicyNbr;
	}

	public String getOctQuoteNbr() {
		return this.octQuoteNbr;
	}

	public void setOctQuoteNbr(String octQuoteNbr) {
		this.octQuoteNbr = octQuoteNbr;
	}

	public String getOctSourceAppCd() {
		return this.octSourceAppCd;
	}

	public void setOctSourceAppCd(String octSourceAppCd) {
		this.octSourceAppCd = octSourceAppCd;
	}

	public BigDecimal getOctTransAmt() {
		return this.octTransAmt;
	}

	public void setOctTransAmt(BigDecimal octTransAmt) {
		this.octTransAmt = octTransAmt;
	}

	public String getOctTrackingNbr() {
		return this.octTrackingNbr;
	}

	public void setOctTrackingNbr(String octTrackingNbr) {
		this.octTrackingNbr = octTrackingNbr;
	}

	public String getOctMerchantNbr() {
		return this.octMerchantNbr;
	}

	public void setOctMerchantNbr(String octMerchantNbr) {
		this.octMerchantNbr = octMerchantNbr;
	}

	public String getOctTransStatusCd() {
		return this.octTransStatusCd;
	}

	public void setOctTransStatusCd(String octTransStatusCd) {
		this.octTransStatusCd = octTransStatusCd;
	}

	public String getOctInsuredStCd() {
		return this.octInsuredStCd;
	}

	public void setOctInsuredStCd(String octInsuredStCd) {
		this.octInsuredStCd = octInsuredStCd;
	}

	public String getOctTransStatusDesc() {
		return this.octTransStatusDesc;
	}

	public void setOctTransStatusDesc(String octTransStatusDesc) {
		this.octTransStatusDesc = octTransStatusDesc;
	}

	public String getOctInsuredFrstNm() {
		return this.octInsuredFrstNm;
	}

	public void setOctInsuredFrstNm(String octInsuredFrstNm) {
		this.octInsuredFrstNm = octInsuredFrstNm;
	}

	public String getOctInsuredMidNm() {
		return this.octInsuredMidNm;
	}

	public void setOctInsuredMidNm(String octInsuredMidNm) {
		this.octInsuredMidNm = octInsuredMidNm;
	}

	public String getOctInsuredLastNm() {
		return this.octInsuredLastNm;
	}

	public void setOctInsuredLastNm(String octInsuredLastNm) {
		this.octInsuredLastNm = octInsuredLastNm;
	}

	public Character getOctSettleInd() {
		return this.octSettleInd;
	}

	public void setOctSettleInd(Character octSettleInd) {
		this.octSettleInd = octSettleInd;
	}

	public Date getOctTransDt() {
		return this.octTransDt;
	}

	public void setOctTransDt(Date octTransDt) {
		this.octTransDt = octTransDt;
	}

	public Date getOctSettledDt() {
		return this.octSettledDt;
	}

	public void setOctSettledDt(Date octSettledDt) {
		this.octSettledDt = octSettledDt;
	}

	public String getOctSettleBatchNbr() {
		return this.octSettleBatchNbr;
	}

	public void setOctSettleBatchNbr(String octSettleBatchNbr) {
		this.octSettleBatchNbr = octSettleBatchNbr;
	}

	public String getOctTransUserId() {
		return this.octTransUserId;
	}

	public void setOctTransUserId(String octTransUserId) {
		this.octTransUserId = octTransUserId;
	}

	public Date getOctCreatedDt() {
		return this.octCreatedDt;
	}

	public void setOctCreatedDt(Date octCreatedDt) {
		this.octCreatedDt = octCreatedDt;
	}

	public Date getOctModifiedDt() {
		return this.octModifiedDt;
	}

	public void setOctModifiedDt(Date octModifiedDt) {
		this.octModifiedDt = octModifiedDt;
	}

	public String getOctModifiedUserId() {
		return this.octModifiedUserId;
	}

	public void setOctModifiedUserId(String octModifiedUserId) {
		this.octModifiedUserId = octModifiedUserId;
	}

	public String getOctAppId() {
		return this.octAppId;
	}

	public void setOctAppId(String octAppId) {
		this.octAppId = octAppId;
	}

	public Set<OneshotTransRev> getOneshotTransRevs() {
		return this.oneshotTransRevs;
	}

	public void setOneshotTransRevs(Set<OneshotTransRev> oneshotTransRevs) {
		this.oneshotTransRevs = oneshotTransRevs;
	}

}
