package OneToMany;



// Generated May 24, 2011 7:06:05 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * OneshotTransRev generated by hbm2java
 */
public class OneshotTransRev implements java.io.Serializable {

	private BigDecimal otrRevSeqNbr;
	private BatchFile batchFileByBafSettleFileSeqNbr;
	private BatchFile batchFileByBafReturnFileSeqNbr;
	private OneshotCcTrans oneshotCcTrans;
	private String otrRevTrackingNbr;
	private BigDecimal otrRevAmt;
	private Date otrCardRevDt;
	private Date otrRevSettledDt;
	private String otrRevUserId;
	private String otrSettleBatchNbr;
	private Date otrCreatedDt;
	private Date otrModifiedDt;
	private String otrModifiedUserId;

	public OneshotTransRev() {
	}

	public OneshotTransRev(BigDecimal otrRevSeqNbr) {
		this.otrRevSeqNbr = otrRevSeqNbr;
	}

	public OneshotTransRev(BigDecimal otrRevSeqNbr,
			BatchFile batchFileByBafSettleFileSeqNbr,
			BatchFile batchFileByBafReturnFileSeqNbr,
			OneshotCcTrans oneshotCcTrans, String otrRevTrackingNbr,
			BigDecimal otrRevAmt, Date otrCardRevDt, Date otrRevSettledDt,
			String otrRevUserId, String otrSettleBatchNbr, Date otrCreatedDt,
			Date otrModifiedDt, String otrModifiedUserId) {
		this.otrRevSeqNbr = otrRevSeqNbr;
		this.batchFileByBafSettleFileSeqNbr = batchFileByBafSettleFileSeqNbr;
		this.batchFileByBafReturnFileSeqNbr = batchFileByBafReturnFileSeqNbr;
		this.oneshotCcTrans = oneshotCcTrans;
		this.otrRevTrackingNbr = otrRevTrackingNbr;
		this.otrRevAmt = otrRevAmt;
		this.otrCardRevDt = otrCardRevDt;
		this.otrRevSettledDt = otrRevSettledDt;
		this.otrRevUserId = otrRevUserId;
		this.otrSettleBatchNbr = otrSettleBatchNbr;
		this.otrCreatedDt = otrCreatedDt;
		this.otrModifiedDt = otrModifiedDt;
		this.otrModifiedUserId = otrModifiedUserId;
	}

	public BigDecimal getOtrRevSeqNbr() {
		return this.otrRevSeqNbr;
	}

	public void setOtrRevSeqNbr(BigDecimal otrRevSeqNbr) {
		this.otrRevSeqNbr = otrRevSeqNbr;
	}

	public BatchFile getBatchFileByBafSettleFileSeqNbr() {
		return this.batchFileByBafSettleFileSeqNbr;
	}

	public void setBatchFileByBafSettleFileSeqNbr(
			BatchFile batchFileByBafSettleFileSeqNbr) {
		this.batchFileByBafSettleFileSeqNbr = batchFileByBafSettleFileSeqNbr;
	}

	public BatchFile getBatchFileByBafReturnFileSeqNbr() {
		return this.batchFileByBafReturnFileSeqNbr;
	}

	public void setBatchFileByBafReturnFileSeqNbr(
			BatchFile batchFileByBafReturnFileSeqNbr) {
		this.batchFileByBafReturnFileSeqNbr = batchFileByBafReturnFileSeqNbr;
	}

	public OneshotCcTrans getOneshotCcTrans() {
		return this.oneshotCcTrans;
	}

	public void setOneshotCcTrans(OneshotCcTrans oneshotCcTrans) {
		this.oneshotCcTrans = oneshotCcTrans;
	}

	public String getOtrRevTrackingNbr() {
		return this.otrRevTrackingNbr;
	}

	public void setOtrRevTrackingNbr(String otrRevTrackingNbr) {
		this.otrRevTrackingNbr = otrRevTrackingNbr;
	}

	public BigDecimal getOtrRevAmt() {
		return this.otrRevAmt;
	}

	public void setOtrRevAmt(BigDecimal otrRevAmt) {
		this.otrRevAmt = otrRevAmt;
	}

	public Date getOtrCardRevDt() {
		return this.otrCardRevDt;
	}

	public void setOtrCardRevDt(Date otrCardRevDt) {
		this.otrCardRevDt = otrCardRevDt;
	}

	public Date getOtrRevSettledDt() {
		return this.otrRevSettledDt;
	}

	public void setOtrRevSettledDt(Date otrRevSettledDt) {
		this.otrRevSettledDt = otrRevSettledDt;
	}

	public String getOtrRevUserId() {
		return this.otrRevUserId;
	}

	public void setOtrRevUserId(String otrRevUserId) {
		this.otrRevUserId = otrRevUserId;
	}

	public String getOtrSettleBatchNbr() {
		return this.otrSettleBatchNbr;
	}

	public void setOtrSettleBatchNbr(String otrSettleBatchNbr) {
		this.otrSettleBatchNbr = otrSettleBatchNbr;
	}

	public Date getOtrCreatedDt() {
		return this.otrCreatedDt;
	}

	public void setOtrCreatedDt(Date otrCreatedDt) {
		this.otrCreatedDt = otrCreatedDt;
	}

	public Date getOtrModifiedDt() {
		return this.otrModifiedDt;
	}

	public void setOtrModifiedDt(Date otrModifiedDt) {
		this.otrModifiedDt = otrModifiedDt;
	}

	public String getOtrModifiedUserId() {
		return this.otrModifiedUserId;
	}

	public void setOtrModifiedUserId(String otrModifiedUserId) {
		this.otrModifiedUserId = otrModifiedUserId;
	}

}
