package OneToMany;



// Generated May 24, 2011 7:06:05 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SecureDataVault generated by hbm2java
 */
public class SecureDataVault implements java.io.Serializable {

	private BigDecimal sdvVaultSeqNbr;
	private String sdvKeyId;
	private String sdvSecureDataTxt;
	private String sdvSecureTokenId;
	private Date sdvCreatedDt;
	private String sdvCreatedUserId;
	private Date sdvPurgeDt;
	private String sdvAppId;
	private Set<CreditCardInfo> creditCardInfos = new HashSet<CreditCardInfo>(0);

	public SecureDataVault() {
	}

	public SecureDataVault(BigDecimal sdvVaultSeqNbr) {
		this.sdvVaultSeqNbr = sdvVaultSeqNbr;
	}

	public SecureDataVault(BigDecimal sdvVaultSeqNbr, String sdvKeyId,
			String sdvSecureDataTxt, String sdvSecureTokenId,
			Date sdvCreatedDt, String sdvCreatedUserId, Date sdvPurgeDt,
			String sdvAppId, Set<CreditCardInfo> creditCardInfos) {
		this.sdvVaultSeqNbr = sdvVaultSeqNbr;
		this.sdvKeyId = sdvKeyId;
		this.sdvSecureDataTxt = sdvSecureDataTxt;
		this.sdvSecureTokenId = sdvSecureTokenId;
		this.sdvCreatedDt = sdvCreatedDt;
		this.sdvCreatedUserId = sdvCreatedUserId;
		this.sdvPurgeDt = sdvPurgeDt;
		this.sdvAppId = sdvAppId;
		this.creditCardInfos = creditCardInfos;
	}

	public BigDecimal getSdvVaultSeqNbr() {
		return this.sdvVaultSeqNbr;
	}

	public void setSdvVaultSeqNbr(BigDecimal sdvVaultSeqNbr) {
		this.sdvVaultSeqNbr = sdvVaultSeqNbr;
	}

	public String getSdvKeyId() {
		return this.sdvKeyId;
	}

	public void setSdvKeyId(String sdvKeyId) {
		this.sdvKeyId = sdvKeyId;
	}

	public String getSdvSecureDataTxt() {
		return this.sdvSecureDataTxt;
	}

	public void setSdvSecureDataTxt(String sdvSecureDataTxt) {
		this.sdvSecureDataTxt = sdvSecureDataTxt;
	}

	public String getSdvSecureTokenId() {
		return this.sdvSecureTokenId;
	}

	public void setSdvSecureTokenId(String sdvSecureTokenId) {
		this.sdvSecureTokenId = sdvSecureTokenId;
	}

	public Date getSdvCreatedDt() {
		return this.sdvCreatedDt;
	}

	public void setSdvCreatedDt(Date sdvCreatedDt) {
		this.sdvCreatedDt = sdvCreatedDt;
	}

	public String getSdvCreatedUserId() {
		return this.sdvCreatedUserId;
	}

	public void setSdvCreatedUserId(String sdvCreatedUserId) {
		this.sdvCreatedUserId = sdvCreatedUserId;
	}

	public Date getSdvPurgeDt() {
		return this.sdvPurgeDt;
	}

	public void setSdvPurgeDt(Date sdvPurgeDt) {
		this.sdvPurgeDt = sdvPurgeDt;
	}

	public String getSdvAppId() {
		return this.sdvAppId;
	}

	public void setSdvAppId(String sdvAppId) {
		this.sdvAppId = sdvAppId;
	}

	public Set<CreditCardInfo> getCreditCardInfos() {
		return this.creditCardInfos;
	}

	public void setCreditCardInfos(Set<CreditCardInfo> creditCardInfos) {
		this.creditCardInfos = creditCardInfos;
	}

}
